### ISSUE TITLE
Please make a plugin.yml file for this, and package this into a jar file

### ISSUE THREAD

**Issue by maxxie114** [SumWum/AAF#1]
1. You need a plugin.yml for Nukkit to be able to run the plugin.
2. The file format looks something like this:
Plugin.jar
    --Manifest.MF
    --plugin.yml
    --src
       ----File1.java
       ----File2.java

**Comment by SumWum** [comment]
I can add the plugin.yml although I'll have to regenerate it.

the jar is already under releases but I'll add it again in one big package.

I tested the plugin on my own nukkit server (the test one) as it is under releases and it worked fine.

**Comment by SumWum** [comment]
check releases
